'use client';
import CitationCard from './CitationCard';
import ConfidenceScore from './ConfidenceScore';
import RiskMeter from './RiskMeter';
import ComparisonTable from './ComparisonTable';
import {describeMode,safeSourceUrl} from '@/services/protocol.mjs';
const text=(v:any):string=>typeof v==='string'?v:JSON.stringify(v);
export function Notice({children,type='notice'}:{children:React.ReactNode,type?:string}) {return <div className={`notice ${type}`} role={type==='error'?'alert':'status'}>{children}</div>;}
type EmptyAction={label:string;href?:string;onClick?:()=>void};
export function Empty({title='No assessment yet',children,action}:{title?:string,children?:React.ReactNode,action?:EmptyAction}) {const defaults:Record<string,EmptyAction>={'No assessment yet':{label:'Complete screening form',href:'#screening-form'},'No saved reports yet':{label:'Start a screening',href:'/ask'},'No stored changes to compare':{label:'Open source library',href:'/knowledge-library'},'No records returned':{label:'Refine screening',href:'#screening-form'},'No requirements to screen':{label:'Compare regulations',href:'/regulation-compare'}};const resolvedAction=action||defaults[title];return <div className="empty-state"><span className="empty-icon" aria-hidden="true">◇</span><strong>{title}</strong><p>{children||'Enter your information and run a screen. Evidence and limitations will appear here.'}</p>{resolvedAction&&(resolvedAction.onClick?<button className="button primary small empty-cta" onClick={resolvedAction.onClick}>{resolvedAction.label}</button>:<a className="button primary small empty-cta" href={resolvedAction.href}>{resolvedAction.label}</a>)}</div>;}
export default function ResultView({result}:{result:any}) {
 if(!result)return <Empty/>;
 const nested=result.routing?result.results?.[result.routing.primary]:null;
 const data=nested||result;
 const mode=data.mode||data.search_summary?.provider_mode||result.mode||'local';
 const citations=result.citations?.length?result.citations:data.citations||[];
 const trust=result.trust||data.trust;
 const patent=data.assessment?.readiness;
 const prior=Array.isArray(data.results)&&data.search_summary?data.results:null;
 return <div className="result-view"><div className="result-top"><h2>Screening result</h2><span className={`badge ${mode==='mock'?'warning':''}`}>{describeMode(mode)}</span></div>
 {mode==='mock'&&<Notice type="warning"><strong>TEST DATA ONLY.</strong> These records demonstrate the workflow. They are not real patents, regulatory requirements or TKDL evidence.</Notice>}
 <div className="answer-card"><span className="eyebrow">{(result.status||data.status||'screening').replaceAll('_',' ')}</span><p className="answer-text">{result.answer||data.risk?.conclusion||'Review the screened information, supporting excerpts and gaps below. Professional verification is required.'}</p></div>
 {(trust||patent||data.risk||data.score)&&<div className="score-grid">{trust&&<><ConfidenceScore label="Trust score" score={trust.trust_score}/><ConfidenceScore label="Evidence strength" score={trust.evidence_score} description={trust.evidence_strength||'Grounding and source quality only.'}/></>}{patent&&<ConfidenceScore label="Patent screening readiness" score={patent.score}/>} {data.score&&<ConfidenceScore score={data.score.score} label={data.score.name} description={data.score.meaning}/>} {data.risk&&<RiskMeter score={data.risk.score} level={data.risk.level} label={data.risk.name||'Detected overlap'}/>}</div>}
 {data.extracted&&<section className="panel inset"><h3>Extracted from your description</h3><div className="extraction-grid">{Object.entries(data.extracted).map(([key,items])=><div key={key}><span className="field-label">{key.replaceAll('_',' ')}</span><div className="chips">{(items as any[]).length?(items as any[]).map((item,i)=><span className="chip" key={i}>{item.canonical}{item.negated?' · negated mention':''}<small>{item.original}</small></span>):<span className="muted">No recognized mention</span>}</div></div>)}</div></section>}
 {data.invention&&<section className="panel inset"><h3>Invention profile</h3><dl className="details-grid">{Object.entries(data.invention).filter(([,v])=>v&&(!Array.isArray(v)||v.length)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{Array.isArray(v)?v.join(' · '):text(v)}</dd></div>)}</dl></section>}
 {data.assessment?.novelty&&<div className="two-columns">{['novelty','inventive_step'].map(k=><section className="panel inset" key={k}><h3>{k.replaceAll('_',' ')}</h3><p>{data.assessment[k]?.summary||data.assessment[k]?.explanation||data.assessment[k]?.status?.replaceAll('_',' ')}</p><details><summary>Assessment detail</summary><pre>{JSON.stringify(data.assessment[k],null,2)}</pre></details></section>)}</div>}
 {data.evidence_gaps?.length>0&&<section className="panel inset"><h3>Evidence gaps</h3><ul className="checklist">{data.evidence_gaps.map((g:any,i:number)=><li key={i}>{text(g)}</li>)}</ul></section>}
 {data.recommended_next_steps?.length>0&&<section className="panel inset"><h3>Recommended review steps</h3><ul className="checklist">{data.recommended_next_steps.map((g:any,i:number)=><li key={i}>{text(g)}</li>)}</ul></section>}
 {prior&&<section><h3>Prior-art search records <span className="count">{prior.length}</span></h3>{!prior.length&&<Empty title="No records returned">A search with no results does not establish novelty.</Empty>}{prior.map((p:any,i:number)=><article className="patent-record" key={i}><div className="row-between"><span className="eyebrow">RANK {p.rank} · {p.publication_number||'Identifier unavailable'}</span><span className="badge">Similarity {p.similarity?.overall_similarity??'—'}/100</span></div><h3>{p.title||'Title unavailable'}</h3><p>{p.abstract||'Abstract unavailable from this provider.'}</p><div className="meta-row"><span>{p.jurisdiction||'Jurisdiction unavailable'}</span><span>Published: {p.publication_date||'Unavailable'}</span><span>{p.provider}</span></div><div className="chips">{p.feature_overlap?.matching_features?.map((f:string)=><span className="chip" key={f}>{f}</span>)}</div>{safeSourceUrl(p.source_url)?<a href={safeSourceUrl(p.source_url)!} target="_blank" rel="noreferrer">Open supplied source ↗</a>:<small>No source URL was supplied. Use the publication identifier to inspect the record.</small>}</article>)}</section>}
 {data.matches?.length>0&&<section><h3>Traditional knowledge review leads</h3>{data.matches.map((m:any,i:number)=><article className="panel inset" key={i}><div className="row-between"><strong>{m.record_id}</strong><span className="badge">Feature overlap {m.similarity.score}/100</span></div><div className="chips">{Object.values(m.similarity.features).flatMap((f:any)=>f.matched).map((v:any,i:number)=><span className="chip" key={i}>{v}</span>)}</div><CitationCard citation={m.evidence} index={i}/></article>)}</section>}
 {data.rows&&<section><h3>Jurisdiction comparison</h3>{data.coverage&&<div className="chips">{Object.entries(data.coverage).map(([j,covered])=><span className={`chip ${!covered?'warning':''}`} key={j}>{j}: {covered?'Stored sources available':'Evidence missing'}</span>)}</div>}<ComparisonTable rows={data.rows} jurisdictions={data.jurisdictions}/></section>}
 {data.checks&&<section><h3>Document requirement checks</h3>{data.checks.length?<div className="table-scroll"><table><thead><tr><th>Requirement</th><th>Supplied information</th><th>Screening status</th><th>Source</th></tr></thead><tbody>{data.checks.map((c:any,i:number)=><tr key={i}><th>{c.label}</th><td>{c.supplied_value===null||c.supplied_value===undefined?'—':text(c.supplied_value)}</td><td><span className={`badge ${c.status==='missing'||c.status==='rule_mismatch'?'warning':''}`}>{c.status.replaceAll('_',' ')}</span></td><td>{c.evidence_id}<small>{c.version}</small></td></tr>)}</tbody></table></div>:<Empty title="No requirements to screen">Supply a current, applicable regulatory corpus. This is not a compliance clearance.</Empty>}</section>}
 {data.steps&&<section><h3>Your compliance journey</h3><ol className="journey">{data.steps.map((s:any,i:number)=><li key={s.id}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{s.title}</strong><small>{s.status.replaceAll('_',' ')}{s.depends_on.length?` · After: ${s.depends_on.join(', ')}`:''}</small>{s.evidence_ids?.length>0&&<p className="muted">Evidence: {s.evidence_ids.join(', ')}</p>}</div></li>)}</ol></section>}
 {result.routing&&Object.keys(result.results||{}).length>1&&<section><h3>Additional agent results</h3>{Object.entries(result.results).filter(([name])=>name!==result.routing.primary).map(([name,value])=><details className="panel inset" key={name}><summary>{name.replaceAll("_"," ")}</summary><ResultView result={value}/></details>)}</section>}
 {result.trace&&<details className="panel inset"><summary>Agent routing and evidence checks</summary><div className="trace">{result.trace.map((t:any,i:number)=><span key={i}>{t.agent.replaceAll('_',' ')}<small>{t.status.replaceAll('_',' ')}</small></span>)}</div></details>}
 {citations.length>0&&<section><div className="section-title"><h3>Citations & source excerpts</h3><span className="count">{citations.length} sources</span></div><div className="source-grid">{citations.map((c:any,i:number)=><CitationCard key={i} citation={c} index={i}/>)}</div></section>}
 {!citations.length&&!prior&&<Notice>No source excerpts are available for this result. No definitive conclusion should be drawn.</Notice>}
 <details className="limitations" open><summary>Scope & limitations</summary><ul>{Array.from(new Set([...(result.limitations||[]),...(data.limitations||[])])).map((v:any,i)=><li key={i}>{text(v)}</li>)}<li>No real prior-art search → no final novelty claim. No authorized TK search → no final TK clearance.</li></ul></details><details className="raw-detail"><summary>View full structured response</summary><pre>{JSON.stringify(result,null,2)}</pre></details></div>;
}
