export type ScenePhase = 'idle' | 'input' | 'submitting' | 'processing' | 'success' | 'partial' | 'error';
export type ProviderTone = 'ready' | 'partial' | 'unavailable' | 'neutral';
export type SceneSignal = {
  route: string;
  fromRoute: string;
  toRoute: string;
  transitionStartedAt: number;
  direction: -1 | 0 | 1;
  transitionRevision: number;
  phase: ScenePhase;
  phaseStartedAt: number;
  pulseAt: number;
  pulseKind: string;
  nodeCount?: number;
  density?: number;
  score?: number;
  jurisdictions: string[];
  hover: string;
  providerTone: ProviderTone;
  riskTone?: 'low' | 'medium' | 'high';
  documentSelected: boolean;
};
export type SceneTransitionState = Pick<SceneSignal, 'route' | 'fromRoute' | 'toRoute' | 'transitionStartedAt' | 'direction' | 'transitionRevision'>;
export const WORKSPACE_ROUTE_GROUPS: ReadonlyArray<readonly [string, readonly string[]]>;
export const WORKSPACE_ROUTE_ORDER: readonly string[];
export function normalizeSceneRoute(value: unknown): string;
export function sceneTransitionDirection(fromRoute: string, toRoute: string): -1 | 0 | 1;
export function createSceneTransitionState(route?: string): SceneTransitionState;
export function reduceSceneTransition(state: SceneTransitionState, toRoute: string, at: number, confirmation?: boolean): SceneTransitionState;
export function normalizeSceneCount(value: unknown, cap?: number): number | undefined;
export function normalizeSceneScore(value: unknown): number | undefined;
export function normalizeJurisdictions(value: unknown): string[];
export function normalizeProviderTone(value: unknown): ProviderTone;
export function normalizeRiskTone(value: unknown): 'low' | 'medium' | 'high' | undefined;
export function getSceneSignal(): SceneSignal;
export function setSceneRoute(route: string): void;
export function beginSceneTransition(toRoute: string): boolean;
export function setScenePhase(phase: ScenePhase, pulseKind?: string): void;
export function pulseScene(kind?: string): void;
export function setSceneMetrics(patch: Partial<Pick<SceneSignal, 'nodeCount' | 'density' | 'score' | 'jurisdictions' | 'providerTone' | 'riskTone' | 'documentSelected'>>): void;
export function setSceneHover(value?: string): void;
